# Generated by Django 5.0.6 on 2024-05-25 00:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Age')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('phone_number2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number 2')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('announcement', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Announcement')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Summary')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('blog', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Blog')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=100, null=True, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Summary')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Subject Name')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Teacher', 'Teacher'), ('Bursary', 'Bursary'), ('Library', 'Library')], max_length=50, null=True, verbose_name='Staff Role')),
                ('salary', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Salary Amount')),
                ('bank', models.CharField(choices=[('Teacher', 'Teacher'), ('Bursary', 'Bursary'), ('Library', 'Library')], max_length=50, null=True, verbose_name='Staff Role')),
                ('account_number', models.CharField(choices=[('Teacher', 'Teacher'), ('Bursary', 'Bursary'), ('Library', 'Library')], max_length=50, null=True, verbose_name='Staff Role')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Graduate', 'Graduate'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled')], max_length=100, null=True, verbose_name='Status')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_portal_app.class')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_portal_app.student')),
                ('subject', models.ForeignKey(choices=[('Ongoing', 'Ongoing'), ('Graduate', 'Graduate'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled')], on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school_portal_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='school_portal_app.subject'),
        ),
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Paid Balance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], max_length=50, verbose_name='Payment Status')),
                ('method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal_app.student')),
            ],
        ),
    ]
