# Generated by Django 4.2.8 on 2024-05-18 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('announcement', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Announcement')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Summary')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('blog', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Blog')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Summary')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='First Name')),
                ('other_name', models.CharField(max_length=100, null=True, verbose_name='Other Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('email_address', models.CharField(max_length=100, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=100, null=True, verbose_name='Phone Number')),
                ('age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Age')),
                ('role', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=50, null=True, verbose_name='Staff Role')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bank', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=50, null=True, verbose_name='Staff Role')),
                ('account_number', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=50, null=True, verbose_name='Staff Role')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('other_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guardian Phone Number')),
                ('phone_number2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guardian Phone Number')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Age')),
                ('student_class', models.CharField(choices=[('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=50, null=True, verbose_name='Class')),
                ('status', models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Graduate', 'Graduate'), ('Suspended', 'Suspended'), ('Expelled', 'Expelled')], max_length=100, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Subject Name')),
                ('student_class', models.CharField(choices=[('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SSS 1', 'SSS 1'), ('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=50, null=True, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Paid Balance')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS')], max_length=50, verbose_name='Payment Status')),
                ('method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal_app.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_portal_app.subject'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_portal_app.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school_portal_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_portal_app.blogs')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
