# Generated by Django 4.2.8 on 2024-04-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='School Name')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slogan')),
                ('overview', models.CharField(blank=True, max_length=100, null=True, verbose_name='Overview')),
                ('about', models.CharField(blank=True, max_length=1000, null=True, verbose_name='About')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
