# Generated by Django 4.2.8 on 2024-04-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal_app', '0002_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQS',
            new_name='FAQ',
        ),
    ]
