# Generated by Django 4.2.8 on 2024-04-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal_app', '0003_rename_faqs_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccalender',
            options={'verbose_name_plural': 'Academic Calender'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'School'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='about',
        ),
    ]
