# Generated by Django 4.2.8 on 2024-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal_app', '0004_alter_academiccalender_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='About'),
        ),
    ]
